api/urls.py
# -*- coding:utf-8 -*-
# Author:cqk
# Data:2020/1/8 10:06
from django.conf.urls import url
from api import views
urlpatterns = [
    url(r"^login/$",views.LoginView.as_view()),
    url(r"^mssagecode/$",views.MessageView.as_view()),
    url(r"^credential/$", views.CredentialView.as_view()),
    url(r"^issue/$", views.IssueView.as_view()),
    url(r"^article/$", views.ShowArticlesView.as_view()),
    url(r"^article/(?P<pk>\d+)/$", views.GetArticleDetailView.as_view()),
    url(r"^care/(?P<pk>\d+)/$", views.CareView.as_view()),


    # url(r"^articledetial/(?P<pk>\d+)/$", views.ShowArticleDetailsViews.as_view()),
    url(r"^topic/$", views.TopicView.as_view()),
    url(r"^comment/$", views.CommentView.as_view()),
    url(r"^createarticle/$", views.IssueCreateView.as_view()),

]

auction/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^api/",include("api.urls",namespace="api")),
    url(r"^sale/",include("sale.urls",namespace="sale")),
    url(r"^web/",include("web.urls",namespace="web")),
]

web/urls.py
# -*- coding:utf-8 -*-
# Author:cqk
# Data:2020/2/10 16:37

from django.conf.urls import url,include
from web.views.SaleCategory import SaleCategory_show
from web.views.SaleCategory import auction_item_show
urlpatterns = [
    # 专场
    url(r"^SaleCategory/list/$",SaleCategory_show.show,name="SaleCategory_list"),
    url(r"^SaleCategory/add/$",SaleCategory_show.addeditor,name="SaleCategory_add"),
    url(r"^SaleCategory/editor/(\d+)$",SaleCategory_show.addeditor,name="SaleCategory_editor"),
    url(r"^SaleCategory/del/(\d+)$",SaleCategory_show.delete,name="SaleCategory_del"),

    #拍品
    url(r"^auction/list/(?P<salecategory_id>\d+)/$",auction_item_show.show,name="auction_item_list"),
    url(r"^auction/add/(?P<salecategory_id>\d+)/$",auction_item_show.add,name="auction_item_add"),
    url(r"^auction/editor/(?P<salecategory_id>\d+)/(?P<item_id>\d+)/$",auction_item_show.editor,name="auction_item_editor"),
    url(r"^auction/del/(?P<item_id>\d+)/$",auction_item_show.delete,name="auction_item_del"),

    url(r'^auction/item/detail/add/(?P<item_id>\d+)/$', auction_item_show.information_add,
        name='auction_item_detail_add'),
    url(r'^auction/item/detail/add/one/(?P<item_id>\d+)/$', auction_item_show.information_add_one,
        name='auction_item_detail_add_one'),
    url(r'^auction/item/detail/delete/one/$', auction_item_show.auction_item_detail_delete_one,
        name='auction_item_detail_delete_one'),

    url(r'^auction/item/image/add/(?P<item_id>\d+)/$', auction_item_show.auction_item_image_add, name='auction_item_image_add'),
    url(r'^auction/item/image/add/one/(?P<item_id>\d+)/$', auction_item_show.auction_item_image_add_one,
        name='auction_item_image_add_one'),
    url(r'^auction/item/image/delete/one/$', auction_item_show.auction_item_image_delete_one,
        name='auction_item_image_delete_one'),

]

sale/models.py
from django.db import models


class SaleCategory(models.Model):
    """
    拍卖专场

    首页图片
    首页视频
    title  专场标题
    status 状态 结束  预展中 拍卖中
    starttime 开拍时间
    endtime 结束时间
    拍品数量
    出价次数
    围观次数
    成交额
    全场保证金
    """
    # FileField = 数据保存文件路径CharField + ModelForm显示时File来生成标签 + ModelForm.save()
    image_url = models.FileField(verbose_name="专场首页图片", max_length=256)
    video_url = models.CharField(verbose_name="专场首页视频", max_length=256, null=True, blank=True)
    title = models.CharField(verbose_name="专场标题", max_length=64)
    status_choice = (
        (1, "未开始"),
        (2, "预展中"),
        (3, "拍卖中"),
        (4, "已结束"),

    )
    status = models.IntegerField(verbose_name="状态", choices=status_choice, default=1)
    preview_start_time = models.DateTimeField(verbose_name="预展时间", null=True, blank=True)
    start_time = models.DateTimeField(verbose_name="开始时间")
    end_time = models.DateTimeField(verbose_name="结束时间")

    cash_deposit = models.PositiveIntegerField(verbose_name="全场保证金", default=10000)

    commodity_count = models.PositiveIntegerField(verbose_name="拍品数量", default=0)
    bid_count = models.PositiveIntegerField(verbose_name="出价次数", default=0)
    onlook_count = models.PositiveIntegerField(verbose_name="围观次数", default=0)
    trading_volume = models.PositiveIntegerField(verbose_name="成交金额", default=0)

    class Meta:
        verbose_name_plural = "拍卖专场"

    def __str__(self):
        return self.title
class SaleCategory_task(models.Model):
    salecategory = models.OneToOneField(verbose_name="拍卖专场", to="SaleCategory", on_delete=models.CASCADE,
                                     related_name="salecategory_task")
    preview_start_id = models.CharField(verbose_name="预展任务id",max_length=128,null=True,blank=True)
    start_id = models.CharField(verbose_name="预展任务id",max_length=128,null=True,blank=True)
    end_start_id = models.CharField(verbose_name="预展任务id",max_length=128,null=True,blank=True)

class Commodity(models.Model):
    """
    拍品


    专场  foreign key  SaleCategory
    名称 title
    展示图片 image_url
    视频展示 video_url
    起拍价 starting_price
    当前价格 开始等于起拍价 最终等于成交价 present_price
    成交价 开始为空 transaction_price
    出价次数 bid_count
    单品保证金
    加价幅度
    浏览次数
    图录号
    拍品详情介绍
    """
    salecategory = models.ForeignKey(verbose_name="拍卖专场", to="SaleCategory", on_delete=models.CASCADE,
                                     related_name="commodity")
    title = models.CharField(verbose_name="名称", max_length=64)
    image_url = models.FileField(verbose_name="封面", max_length=256)
    video_url = models.CharField(verbose_name="拍品首页视频", max_length=256, null=True, blank=True)
    status_choices = (
        (1, '未开拍'),
        (2, '预展中'),
        (3, '拍卖中'),
        (4, '成交'),
        (5, '流拍'),
        (6, '逾期未付款'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    starting_price = models.PositiveIntegerField(verbose_name="起拍价", default=0)
    present_price = models.PositiveIntegerField(verbose_name="当前出价价格", default=0)
    transaction_price = models.PositiveIntegerField(verbose_name="成交价格", default=0)
    bid_count = models.PositiveIntegerField(verbose_name="出价次数", default=0)
    cash_deposit = models.IntegerField(verbose_name="单品保证金")
    mark_up = models.PositiveIntegerField(verbose_name="加价幅度", default=100)
    browse_number = models.IntegerField(verbose_name="浏览次数", default=0)
    turing_number = models.CharField(verbose_name="图录号", max_length=64)
    particulars = models.TextField(verbose_name="拍品详情介绍")
    min_price = models.PositiveIntegerField(verbose_name="市场估价最低价")
    max_price = models.PositiveIntegerField(verbose_name="市场估价最高价")

    class Meta:
        verbose_name_plural = "拍品"

    def __str__(self):
        return self.title


class Information(models.Model):
    """
    拍品的参数
    一定有一个 市场参考价格

    关联 拍品
    标题
    内容
    """
    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="标题", max_length=32)
    content = models.CharField(verbose_name="内容", max_length=32)

    class Meta:
        verbose_name_plural = "拍品详细参数"

    def __str__(self):
        return self.title


class CommodityDetails(models.Model):
    """
    拍品的详情图片
    status  1 轮播 2详情(1+2)   3详情
    url
    外键关联商品
    """
    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity", on_delete=models.CASCADE)
    status_choice = (
        (1, "轮播图"),
        (2, "详情介绍"),
        (3, "细节描述")
    )
    status = models.IntegerField(verbose_name="图片位置", choices=status_choice)
    image_url = models.FileField(verbose_name="详情图片", max_length=256)

    class Meta:
        verbose_name_plural = "拍品详细图片"


class BidRecord(models.Model):
    """
    出价记录


    出价人
    出价时间
    拍卖的商品  外键Commodity
    价格
    专场   SaleCategory
    """
    bidder = models.ForeignKey(verbose_name="出价者", to="api.UserInfo", related_name="bidder")
    bid_time = models.DateTimeField(verbose_name="出价时间", auto_now_add=True)
    status_choices = (
        (1, '竞价'),
        (2, '成交'),
        (3, '逾期未付款'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity", on_delete=models.CASCADE)
    bid_price = models.PositiveIntegerField(verbose_name="出价金额")
    salecategory = models.ForeignKey(verbose_name="所属专场", to="SaleCategory", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "出价记录"


class CashDeposit(models.Model):
    """
    保证金记录
    用户
    status  1 全场保证金   2单场保证金
    金额
    专场 外键
    单个拍品  外键
    """
    user = models.ForeignKey(verbose_name="保证金缴纳者", to="api.UserInfo", related_name="cashd_deposit_user")
    status_choice = (
        (2, "全场保证金"),
        (1, "单品保证金")
    )
    status = models.IntegerField(verbose_name="类型", choices=status_choice)
    guarantee_sum = models.PositiveIntegerField(verbose_name="保证金额")
    margin_balance = models.PositiveIntegerField(verbose_name="保证金余额")
    pay_type_choices = (
        (1, '微信'),
        (2, '余额')
    )
    pay_type = models.SmallIntegerField(verbose_name='支付方式', choices=pay_type_choices)

    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity", on_delete=models.CASCADE, null=True, blank=True)
    salecategory = models.ForeignKey(verbose_name="所属专场", to="SaleCategory", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "保证金缴纳记录"


class CareRecord(models.Model):
    """
    收藏浏览记录
    收藏(默认等于False只是浏览  如果收藏改为True)
    浏览
    """
    user = models.ForeignKey(verbose_name="浏览者", to="api.UserInfo", related_name="carerecord_user")
    enshrine = models.BooleanField(verbose_name="是否收藏", default=False)
    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity", on_delete=models.CASCADE)
    salecategory = models.ForeignKey(verbose_name="所属专场", to="SaleCategory", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "收藏浏览记录"


class Pay_Order(models.Model):
    """
    订单类
    """
    user = models.ForeignKey(verbose_name="用户", to="api.UserInfo", related_name="payorder_user")
    commodity = models.ForeignKey(verbose_name="拍品", to="Commodity")
    due_money = models.PositiveIntegerField(verbose_name="应付金额")
    payment = models.PositiveIntegerField(verbose_name="实际付款金额")
    payment_time = models.DateTimeField(verbose_name="订单创建时间", auto_now_add=True)
    deposit = models.ForeignKey(verbose_name='保证金', to='CashDeposit')
    order_number = models.CharField(verbose_name="订单号", null=True, blank=True, max_length=128)
    twenty_four_task_id = models.CharField(verbose_name='24小时后的定时任务id',
                                           max_length=32, null=True, blank=True)
    order_choices = (
        (1, "待支付"),
        (2, "代收货"),
        (3, "已完成"),
        (4, "逾期未付款"),
    )
    order_status = models.IntegerField(verbose_name="订单状态", choices=order_choices, default=1)
    address = models.OneToOneField(verbose_name="送货地址",to="api.Adress",on_delete=models.CASCADE)

class DepositRefundRecord(models.Model):
    """保证金退款记录"""
    uid = models.CharField(verbose_name="流水号",max_length=64)
    status_choices = (
        (1, "待退款"),
        (2, '已退款'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态',
                                              choices=status_choices)
    deposit = models.ForeignKey(verbose_name='保证金', to='CashDeposit')
    amount = models.PositiveIntegerField(verbose_name='退款金额')

class DepositDeduct(models.Model):
    """扣除保证金"""
    order = models.ForeignKey(verbose_name='订单', to='Pay_Order')
    amount = models.PositiveIntegerField(verbose_name='金额')

class Couponcash(models.Model):
    """
    优惠券

    关联用户
    关联订单
    某一专场(有值不通用  ,没有值就是通用的)
    优惠金额
    优惠限制(满多少钱可以使用)
    状态(有效,过期,已使用)
    有效期(开始时间 失效时间)
    """
    user= models.ForeignKey(verbose_name="领取用户",to="api.UserInfo",null=True,blank=True)
    pay_order = models.ForeignKey(verbose_name="订单",to=Pay_Order,null=True,blank=True)
    salecategory = models.ForeignKey(verbose_name="专场",to="SaleCategory",null=True,blank=True)

    discount_money=models.PositiveIntegerField(verbose_name="优惠金额")
    limit_money = models.PositiveIntegerField(verbose_name="满足金额",null=True,blank=True)
    status_choise=(
        (1,"有效"),
        (2,"过期"),
        (3,"已使用")
    )
    status=models.PositiveIntegerField(verbose_name="优惠券状态",choices=status_choise,default=1)
    create_time=models.DateTimeField(verbose_name="有效期起始日期",auto_now_add=True)
    end_time=models.DateTimeField(verbose_name="失效日期")

sale/views/SaleCategory.py
# -*- coding:utf-8 -*-
# Author:cqk
# Data:2020/1/17 14:46
from sale import models
from rest_framework.generics import ListAPIView, RetrieveAPIView

from sale.serializer.SaleCategorySerializer import SaleCategoryModelSerializer, SaleCategoryDetialModelSerializer
from rest_framework.pagination import LimitOffsetPagination


class SaleCategoryLimitOffsetPagination(LimitOffsetPagination):
    default_limit = 1
    limit_query_param = 'limit'
    offset_query_param = 'offset'
    max_limit = 20


class SaleCategoryListView(ListAPIView):
    queryset = models.SaleCategory.objects.all().order_by("-id")
    serializer_class = SaleCategoryModelSerializer
    pagination_class = SaleCategoryLimitOffsetPagination

    def get_queryset(self):

        print(self.request.query_params)
        min_id = self.request.query_params.get("min_id")
        print(min_id)
        max_id = self.request.query_params.get("max_id")
        if min_id:
            return models.SaleCategory.objects.filter(id__lt=min_id).order_by("-id")
        elif max_id:
            return models.SaleCategory.objects.filter(id__gt=max_id).order_by("id")
        else:
            return models.SaleCategory.objects.all().order_by("-id")


class SaleCategoryView(RetrieveAPIView):
    serializer_class = SaleCategoryDetialModelSerializer
    queryset = models.SaleCategory.objects

web/templates/web/SaleCategory_show.html
{% extends 'layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
    <h1>拍卖专场列表</h1>
    <a class="btn btn-success" href="{% url 'web:SaleCategory_add' %}">添加</a>
    <table class="table table-hover table-bordered ">
        <thead>
        <th>封面</th>
        <th>专场</th>
        <th>预展时间</th>
        <th>拍卖时间</th>
        <th>结束时间</th>
        <th>状态</th>
        <th>操作</th>
        </thead>
        <tbody>
        {% for obj in salecategory_objs %}
            <tr>
                <td class="center">
                    <img src="{{ obj.image_url }}" alt="" style="height: 100px">
                </td>
                <td class="center"><a href="{% url 'web:auction_item_list' salecategory_id=obj.id %}">{{ obj.title }}</a></td>

                <td>{{ obj.preview_start_time|date:"Y-m-d H:i" }}</td>
                <td>{{ obj.start_time|date:"Y-m-d H:i" }}</td>
                <td>{{ obj.end_time|date:"Y-m-d H:i"  }}</td>
                 <td>{{ obj.get_status_display }}</td>
                <td>
                    <a class="btn btn-default" href="{% url 'web:SaleCategory_editor' obj.id %}">编辑</a>
                    <a class="btn btn-danger" onclick="removeRow(this,'{% url 'web:SaleCategory_del' obj.id %}')">删除</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}
{% block js %}
 <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

web/templates/web/auction_item_show.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">专场信息</div>
            <div class="panel-body">

                <div class="form-horizontal">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">专场</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ salecategory_obj.title }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label"> </label>
                            <div class="col-sm-10">
                                <p class="form-control-static"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">预展开始</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ salecategory_obj.preview_start_time|date:"Y-m-d H:i" }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">拍卖开始</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ salecategory_obj.start_time|date:"Y-m-d H:i" }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">拍卖结束</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ salecategory_obj.end_time|date:"Y-m-d H:i" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading clearfix">拍品
                <a href="{% url 'web:auction_item_add' salecategory_id=salecategory_obj.id %}"
                   class="btn btn-success btn-xs" style="float: right;">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 添加
                </a>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>封面</th>
                    <th>名称</th>
                    <th>图录号</th>
                    <th>起拍价</th>
                    <th>加价幅度</th>
                    <th>参考价格</th>
                    <th>状态</th>
                </tr>
                </thead>
                <tbody>
                {% for item in commodity_list %}
                    <tr>
                        <td>
                            <a href="{% url 'web:auction_item_editor' salecategory_id=salecategory_obj.id item_id=item.id %}">
                                <img style="height: 60px;" src="{{ item.image_url }}">
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'web:auction_item_editor' salecategory_id=salecategory_obj.id item_id=item.id %}">{{ item.title }}</a>
                        </td>
                        <td>{{ item.turing_number }}</td>
                        <td>{{ item.starting_price }}</td>
                        <td>{{ item.mark_up }}</td>
                        <td>{{ item.min_price }} - {{ item.max_price }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a class="btn btn-danger btn-xs"
                               onclick="removeRow(this,'{% url 'web:auction_item_del' item_id=item.id %}')">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

web/templates/web/salecategory_addeditor.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ title }}专题
        </div>
        <div class="panel-body">

            <form  novalidate method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in salecategory_modelformobj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="text-danger">{{ field.errors.0 }}</span>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <input type="submit" class="btn btn-primary pull-right">
                </div>

            </form>


        </div>
    </div>

{% endblock %}
{% block js %}
<script>
        Date.prototype.Format = function (fmt) { //author: meizz
            var o = {
                "M+": this.getMonth() + 1, //月份
                "d+": this.getDate(), //日
                "h+": this.getHours(), //小时
                "m+": this.getMinutes(), //分
                "s+": this.getSeconds(), //秒
                "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                "S": this.getMilliseconds() //毫秒
            };
            if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            for (var k in o)
                if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
            return fmt;
        };

        $(function () {
            initDatepicker();
        });

        function initDatepicker() {
            $('#id_start_time,#id_end_time,#id_preview_start_time').datetimepicker({
                language: "zh-CN",
                minView: "hour", // month
                sideBySide: true,
                format: 'yyyy-mm-dd hh:ii',
                bootcssVer: 3,
                startDate: new Date(),
                autoclose: true
            })
        }
    </script>
{% endblock %}